ImpulsoGov/ImpulsoPrevine

- package.json
- yarn.lock
Reverts ImpulsoGov/ImpulsoPrevine#16
> Revert "fix srcoll horizontal do seletor de paineis"

- helpers/redirectHome.js
- package.json
- pages/_app.js
- pages/busca-ativa/index.js
- pages/cadastros-duplicados/index.js
- pages/capacitacao/index.js
- pages/capacitacoes/index.js
- pages/conteudo-programatico/index.js
- pages/conteudo/index.js
- pages/inicio/index.js
- yarn.lock
- Protege rotas de listas nominais com redirecionamento para usuários sem perfil de acesso
- Oculta menu de dados restritos para usuários sem perfil de acesso
- Altera largura para mobile de conteúdos em PDF e Quizz
- Altera conteúdo com quizz para visualização na mesma pagina
> protege rotas com listas nominais

- pages/_app.js
- Altera chamada da função que faz o push de dados no data layer para ser executada todas as vezes que houver alteração na sessão
> Fix add user data layer

- helpers/redirectHome.js
- package-lock.json
- package.json
- pages/_app.js
- pages/busca-ativa/index.js
- pages/cadastros-duplicados/index.js
- pages/capacitacao/index.js
- pages/capacitacoes/index.js
- pages/conteudo-programatico/index.js
- pages/conteudo/index.js
- pages/duvidas/index.js
- pages/inicio/index.js
- yarn.lock
Faz alterações para restringir o acesso à trilha de capacitação à determinados perfis de acesso.
> Feat restricao trilha

- package-lock.json
- package.json
- pages/_app.js
- pages/apoio/index.js
- pages/index.js
- yarn.lock
- Adiciona margem na imagem da tela de inicio
- Altera página de apoio
- Não retira banner de vacinação
> Altera tela apoio para nova versão cinza

- pages/analise/index.js
Correção do texto capitação na pré tela
> Correção pré tela

- componentes/GraficoHistoricoDesempenho/GraficoHistoricoDesempenho.jsx
> Ordenação do gráfico histórico de desempenho 

- componentes/TabelaIndicadores/TabelaIndicadores.jsx
- componentes/TabelaIndicadores/Tabelas.module.css
Alteração da tabela indicadores, adição da coluna numerador e ajuste na ordenação
> Alteracao tabela indicadores

- pages/dadoPublicos/index.js
Alteração do texto para melhor entendimento do usuario
> Alteração do texto sobre o seletor

- pages/index.js
Adiciona banner do webnar de pre-natal
> add banner webnar pre-natal

- pages/capacitacao/index.js
- pages/duvidas/index.js
Altera link botão voltar da pagina de duvidas
> altera link botao voltar pagina duvidas

- .gitignore
- package.json
- pages/_app.js
- yarn.lock
Temos uma necessidade importante em ter mais ferramentas de Análises para produto. 
Adicionei o hotjar ao ImpulsoPrevine visando capturar todas as sessões da área aberta e área logada.
> 📈 add hotjar to site

- pages/_app.js
Altera texto dos itens do menu dropdown em Dados restritos na barra de navegação no modo logada
> altera texto menu dropdown

- constants/API_URL.js
> altera api-url

- constants/API_URL.js
> rollback url

- componentes/cadastros/index.js
altera copy aviso na aba de capitação ponderada
> altera copy

- pages/index.js
> remove-modal-webnar

- .vscode/settings.json
- package.json
- pages/_app.js
- services/validateCredentials.js
- yarn.lock
Integração inicial com Mixpanel
- Instalado sdk javascript do Mixpanel
- Instanciado objeto client para uso dos métodos
- Enviado evento de Page View, Identify e Update de dados do user profile
> ✨ integração v0 com mixpanel

- pages/_app.js
- Adicionado env var para configurar token do mixpanel
- corrigido o envio da property: logged
> Adjust events mixpanel

- componentes/GraficoEvolucaoEquipe/GraficoEvolucaoEquipe.jsx
- componentes/GraficoEvolucaoEquipe/GraficoEvolucaoEquipe.module.css
- componentes/GraficoEvolucaoEquipe/index.js
- componentes/GraficoFichaProducao/GraficoFichaProducao.jsx
- componentes/GraficoFichaProducao/GraficoFichaProducao.module.css
- componentes/GraficoFichaProducao/index.js
- componentes/GraficoSuasEquipes/GraficoSuasEquipes.jsx
- componentes/GraficoSuasEquipes/index.js
- componentes/TabelaCadastroPreliminar/TabelaCadastroPreliminar.jsx
- componentes/TabelaCadastroPreliminar/TabelaCadastroPreliminar.module.css
- componentes/TabelaCadastroPreliminar/index.js
- componentes/TabelaDesempenhoEquipes/TabelaDesempenhoEquipes.jsx
- componentes/TabelaDesempenhoEquipes/TabelaDesempenhoEquipes.module.css
- componentes/TabelaDesempenhoEquipes/index.js
- componentes/TabelaFichasCadastro/TabelaFichasCadastro.jsx
- componentes/TabelaFichasCadastro/TabelaFichasCadastro.module.css
- componentes/TabelaFichasCadastro/index.js
- componentes/cadastros/index.js
- package-lock.json
- package.json
- pages/_app.js
- pages/dadoPublicos/index.js
- services/capitacao_ponderada_cadastros_por_equipe.js
- services/capitacao_ponderada_contagem_equipes.js
- services/capitacao_ponderada_validacao_producao.js
- services/capitacao_ponderada_validacao_producao_aplicada.js
Ajuste no tempo de desemprenho da tela capitação ponderada
> Tela Capitação ponderada

- componentes/mounted/busca-ativa/gestantes/APS/GestantesSemDUM/GestantesSemDum.js
- componentes/mounted/busca-ativa/gestantes/APS/indicador_1/grafico_indicador_1_atual.js
- componentes/mounted/busca-ativa/gestantes/APS/indicador_1/grafico_indicador_1_futuro.js
- componentes/mounted/busca-ativa/gestantes/APS/indicador_1/tabelas/GestantesAtivas.js
- componentes/mounted/busca-ativa/gestantes/APS/indicador_1/tabelas/GestantesEncerradas.js
- componentes/mounted/busca-ativa/gestantes/APS/indicador_2/grafico_indicador_2_futuro.js
- componentes/mounted/busca-ativa/gestantes/APS/indicador_2/tabelas/GestantesAtivas.js
- componentes/mounted/busca-ativa/gestantes/APS/indicador_2/tabelas/GestantesEncerradas.js
- componentes/mounted/busca-ativa/gestantes/APS/indicador_3/tabelas/GestantesAtivas.js
- componentes/mounted/busca-ativa/gestantes/APS/indicador_3/tabelas/GestantesEncerradas.js
- data/faixa_etarias.json
- helpers/FiltrosOrdenacaoAux.js
- helpers/colunasGestantes.js
- helpers/colunasGestantesSemDUMAPS.js
- package.json
- pages/_app.js
- pages/busca-ativa/citopatologico/index.js
- yarn.lock
- Ajustes nos botões de ordenação painel de gestantes
> Ajustes pos deploy gestantes

- componentes/GraficoDesempenhoMunicipio/GraficoDesempenhoMunicipio.jsx
- componentes/TabelaIndicadores/TabelaIndicadores.jsx
- componentes/indicadores/index.js
Alteração no gráfico e no titulo da tabela da pagina de indicadores de desempenho
> Atualização na pagina do IP

- pages/_app.js
Segue o card do notion com o descritivo de todos os eventos e propriedades a serem inseridas ao mixpanel:
https://www.notion.so/impulsogov/Mapeamento-de-eventos-e-propriedades-para-implementa-o-do-Mixpanel-7b4b46c987e84fb9966fd47c95d1c5e7
Propriedades adicionadas
- usuario_municipio_id_sus
- is_test_user
> [Mixpanel] Adicionando novas propriedades ao User Profile

- helpers/imprimir.js
- package.json
- pages/busca-ativa/citopatologico/index.js
- pages/busca-ativa/diabeticos/index.js
- pages/busca-ativa/gestantes/index.js
- pages/busca-ativa/hipertensos/index.js
- yarn.lock
Descrição dos eventos de click de imprimir no card do notion:
https://www.notion.so/impulsogov/Mapeamento-de-eventos-e-propriedades-para-implementa-o-do-Mixpanel-7b4b46c987e84fb9966fd47c95d1c5e7
> [Mixpanel] Adicionar evento de click em imprimir lista

- pages/apoio/index.js
atualiza link botao de inscricao ultima dobra
> atualiza link botao de inscricao ultima dobra

- pages/busca-ativa/citopatologico/index.js
- pages/busca-ativa/diabeticos/index.js
- pages/busca-ativa/gestantes/index.js
- pages/busca-ativa/hipertensos/index.js
- pages/inicio/index.js
- O time de analise de dados precisa identificar quais abas e sub abas estão sendo acessadas no painel de gestantes.
- Incluir os parâmetros aba e sub-aba na URL de forma dinâmica para que seja identificado pelo time de analise quais abas e sub-abas estão sendo acessadas
- Ao alterar a aba selecionada no painel, o parâmetro correspondente na URL deve ser alterado assim como para as sub-abas
Esse PR não faz mudanças de configuração da aplicação mantida nesse repositório
> altera parametros de URL painel de gestantes

- package.json
- pages/index.js
- yarn.lock
Adiciona banner para webnar
- Divulgação webnar
> banner v2 webnar

- pages/index.js
> remove banner

- pages/inicio/index.js
Mesmas alterações do PR 184 movidas para a área logada
> add banner webnar area logada

- constants/API_URL.js
Com o lançamento da lista de vacinação, as URLs das APIs foram alteradas para testar as mudanças em staging
- Retornar as URLs para seus valores padrão
> Corrige URLs das APIs de usuários e dados nominais

- package.json
- pages/busca-ativa/gestantes/index.js
- yarn.lock
Atualiza versão do design-system
> atualiza ds

- package.json
- yarn.lock
Ao usar as listas nominais, notou-se que a tabela perdia a ordenação aplicada, caso tivesse, após aplicar filtros. Além disso, após limpar a ordenação com filtros já aplicados, a filtragem dos dados era perdida na tabela, mas o componente de filtro ainda mostrava que os filtros estavam aplicados. Logo, é necessário corrigir essa interação entre filtro e ordenação.
- Atualizar design system para puxar os ajustes:
- Manter a ordenação escolhida pelo usuário após filtrar os dados ou limpar os filtros
- Manter os filtros já aplicados pelo usuários após limpar a ordenação
Escolha uma das listas nominais (todas usam o mesmo componente ajustado `PainelBuscaAtiva`) para checar se:
> Ajusta interação de ordenação e filtro nas listas nominais

- package.json
- yarn.lock
Hoje foi evidenciado que, para alguns municípios, o botão de aplicar filtro, no modal do painel de busca ativa, não estava respondendo, como detalhado [aqui](https://impulsogov.slack.com/archives/C04G8VCAC2G/p1709039865837769).
- Atualizar desgin system para a versão nova definida em https://github.com/ImpulsoGov/design-system/pull/167
> [Listas nominais] Corrige botão de aplicar filtros que não respondia

- package.json
- pages/index.js
- pages/inicio/index.js
- yarn.lock
- Adiciona banner de atualização cadastral na home
> Banner atualizacao cadastral

- pages/inicio/index.js
- Altera copy do banner de atualização cadastral
> altera copy banner atualizacao cadastral

- componentes/ButtonColor/ButtonColor.jsx
- componentes/ButtonColor/ButtonColor.module.css
- componentes/ButtonColor/ButtonColor.stories.js
- componentes/ButtonColor/ButtonColorSubmit.stories.js
- componentes/ButtonColor/ButtonColorSubmitMultiple.stories.js
- componentes/ButtonColor/index.js
- componentes/ModalAlert/ModalAlert.jsx
- componentes/ModalAlert/ModalAlert.module.css
- componentes/ModalAlert/ModalAlert.stories.js
- componentes/ModalAlert/ModalAlertV2.module.css
- componentes/ModalAlert/ModalAlertV3.module.css
- componentes/ModalAlert/index.js
- pages/inicio/index.js
O presente PR conserta a seguinte demanda : 
O botão de fechar não estava aparecendo no banner de atualização cadastral na versão mobile.
> fix modal alert

- package.json
- yarn.lock
[Descrição da tarefa](https://www.notion.so/impulsogov/Incluir-comportamento-de-comprimir-lista-de-filtros-quando-uma-nova-expandida-427409c722874bd9943a972ed16d03f2?pvs=4)
- Atualizar design system para incoporar novo comportamento da lista nominal de fechar opções de um filtro quando outro é expandido dentro do modal de filtros
- Acessando uma lista nominal:
> [Quick wins] Fechar filtro da lista nominal quando outro é expandido

- pages/busca-ativa/diabeticos/index.js
- pages/busca-ativa/gestantes/index.js
- pages/busca-ativa/hipertensos/index.js
Descrição da tarefa:  
[Incluir nos painéis legendas de siglas utilizadas](https://www.notion.so/impulsogov/Incluir-nos-pain-is-legendas-de-siglas-utilizadas-2f025ebfe00f4b319d5e436c3091a93d)
Inclusão de legendas das siglas utilizadas na visão de APS e EQUIPE
Acessando as listas:
> [Quick wins] Incluir nos painéis legendas de siglas utilizadas

- src/componentes/mounted/dados-publicos/indicadores/Indicadores.tsx
- src/componentes/mounted/dados-publicos/indicadores/TabelaIndicadores/TabelaIndicadores.jsx
- src/helpers/menuNavBar.ts
[Descrição da tarefa](https://linear.app/impulsogov/issue/ALOG-148/dados-abertos-sisab-atualizacao-do-quadrimestre-para-q224)
> Atualiza textos para Q2 na área aberta

- package.json
- yarn.lock
[Descrição da tarefa](https://linear.app/impulsogov/issue/ALOG-100/implementar-botao-clicavel-na-barra-de-busca)
- Adicionar botão na barra de busca
- Realizar a busca apenas quando houver click no botão ou quando a tecla Enter for pressionada
> Adiciona botão na barra de busca das listas

- src/app/inicio/Inicio.tsx
- src/app/inicio/page.tsx
- src/helpers/inicio/unificarSituacaoPorIndicadores.ts
- src/services/inicio/inicioAPS.ts
Renderização Condicional:
Renderiza o componente <Inicio /> com os dados obtidos se a API retornar resultados.
Exibe mensagem de erro com link para suporte no caso de falha na obtenção dos dados.
> Fix pagina inicio

- __tests__/dadosPublicos/dadosPublicos.test.tsx
- src/app/Base.tsx
- src/middlewares/middlewarePages.ts
[Descrição da tarefa](https://linear.app/impulsogov/issue/ALOG-359/dados-sisab-fora-de-ar-para-acessos-via-area-logada)
> Dados SISAB fora de ar para acessos via Área Logada

- package.json
- yarn.lock
[Descrição da tarefa](https://linear.app/impulsogov/issue/ALOG-196/no-celular-a-barra-de-menu-nao-expande-quando-clica-em-listas-nominais)
> No celular a barra de menu não expande quando clica em "listas nominais"

- src/features/acf/modules/AcfDashboardPage/modules/PanelSelector/modules/dashboards/List.tsx
Remove filtros da tela de lista nominal, considerando que a entrega atual é somente para a tabela.
Fixes ALOG-383
> Remove filtros da nova lista nominal

- src/constants/municipios.js
Realiza troca do nome de município de teste.
Fixes ALOG-383
> feat: troca municipio da demo para Monsenhor Tabosa

- src/features/acf/modules/AcfDashboardPage/modules/PanelSelector/PanelSelector.consts.tsx
- src/features/acf/modules/AcfDashboardPage/modules/PanelSelector/PanelSelector.container.tsx
> Dinamiza nome do municipio

- src/features/acf/modules/AcfDashboardPage/AcfDashboardPage.tsx
- src/features/acf/modules/AcfDashboardPage/modules/PanelSelector/modules/dashboards/List.tsx
- src/features/acf/modules/AcfDashboardPage/modules/PanelSelector/modules/dashboards/modules/urlSearchParamsHook.ts
Inclui novos parâmetros de url
Fixes ALOG-383
> altera parametro de url

- package.json
- src/features/acf/modules/AcfDashboardPage/modules/PanelSelector/PanelSelector.consts.tsx
- src/features/acf/modules/AcfDashboardPage/modules/PanelSelector/PanelSelector.presentation.tsx
- src/features/acf/modules/AcfDashboardPage/modules/PanelSelector/modules/dashboards/List.tsx
- yarn.lock
> Torna aba e sub-abas opcionais

- package.json
- yarn.lock
> Corrige erro no build

- prisma/schema.prisma
Atualiza arquivo schema.prisma com as alterações feitas no banco.
> Atualiza arquivo schema.prisma

- src/helpers/menuNavBar.ts
> feat: adiciona novo  menu

- __tests__/unit/lista-nominal/filters/logic.test.ts
- package.json
- src/features/acf/diabetes/common/schema.ts
- src/features/acf/diabetes/frontend/AcfPage/modules/PanelSelector/modules/dashboards/modules/WithFilters/logic.ts
- yarn.lock
> Atualiza Zod para v4

- package.json
- yarn.lock
> Atualiza typescript para 5.9

- src/features/acf/frontend/common/SearchToolBar/index.tsx
- src/global.d.ts
> Adiciona evento do UserGuiding para disparar banner de impressão

- src/features/acf/frontend/common/Print/modules/PrintTable/container.tsx
- src/features/acf/frontend/common/Print/modules/PrintTable/model.ts
- src/features/acf/frontend/common/Print/modules/PrintTable/modules/MultipleTeamsPerPage.tsx
- src/features/acf/frontend/common/Print/modules/PrintTable/modules/PageHeader.tsx
- src/features/acf/frontend/common/Print/modules/PrintTable/modules/SplitByProp.ts
- src/features/acf/frontend/common/Print/modules/PrintTable/modules/TableCell.tsx
- src/features/acf/frontend/common/Print/modules/PrintTable/modules/Thead.tsx
- src/features/acf/frontend/common/Print/modules/PrintTable/modules/UnitTable.tsx
- src/features/acf/frontend/common/Print/modules/PrintTable/presentation.tsx
- src/features/acf/frontend/common/PrintModal/model.ts
- src/features/acf/frontend/common/WithCustomPrint/index.tsx
- src/features/acf/frontend/hypertension/modules/AcfPage/modules/List/modules/ListCoaps/container.tsx
- src/features/acf/frontend/hypertension/modules/AcfPage/modules/List/modules/ListCoaps/modules/Print/consts.tsx
- src/features/acf/frontend/hypertension/modules/AcfPage/modules/List/modules/ListCoeq/container.tsx
- src/features/acf/frontend/hypertension/modules/AcfPage/modules/List/modules/ListCoeq/modules/Print/consts.tsx
- src/features/acf/shared/schema.ts
> [FEATURE] - Adiciona opção de personalização de impressão - Dividir por propriedade

- src/features/acf/frontend/common/Print/modules/PrintTable/container.tsx
- src/features/acf/frontend/common/Print/modules/PrintTable/presentation.tsx
- src/features/acf/frontend/common/PrintModal/index.tsx
- src/features/acf/frontend/common/PrintModal/modules/CustomPrint/index.tsx
- src/features/acf/frontend/common/SearchToolBar/index.tsx
- src/features/acf/frontend/common/WithSearch/index.tsx
- src/features/acf/frontend/diabetes/modules/AcfPage/modules/List/container.tsx
- src/features/acf/frontend/hypertension/modules/AcfPage/modules/List/modules/ListCoaps/container.tsx
- src/features/acf/frontend/hypertension/modules/AcfPage/modules/List/modules/ListCoeq/container.tsx
> [FIX]  Performance do modal de impressão

- __tests__/integration/api/lista-nominal/hypertension/pages/coaps/[page]/route.test.ts
> Adiciona teste de integração da rota de páginas de hipertensão COAPS

- __tests__/integration/api/lista-nominal/hypertension/pages/coeq/[page]/route.test.ts
> Adiciona teste de integração da rota de páginas de hipertensão COEQ

- __tests__/integration/api/lista-nominal/hypertension/pages/coaps/[page]/route.test.ts
- __tests__/integration/api/lista-nominal/hypertension/pages/coaps/all/route.test.ts
- __tests__/integration/api/lista-nominal/hypertension/pages/coeq/[page]/route.test.ts
- __tests__/integration/api/lista-nominal/hypertension/pages/coeq/all/route.test.ts
- src/features/acf/backend/common/QueryBuilder.ts
- src/features/acf/backend/hypertension/modules/table/adapter.ts
- src/features/acf/backend/hypertension/modules/table/model.ts
- src/features/acf/frontend/hypertension/modules/AcfPage/modules/List/modules/ListCoaps/container.tsx
- src/features/acf/frontend/hypertension/modules/AcfPage/modules/List/modules/ListCoaps/modules/CoapsDataTable/consts.tsx
- src/features/acf/frontend/hypertension/modules/AcfPage/modules/List/modules/ListCoaps/modules/CoapsDataTable/index.tsx
- src/features/acf/frontend/hypertension/modules/AcfPage/modules/List/modules/ListCoeq/container.tsx
- src/features/acf/frontend/hypertension/modules/AcfPage/modules/List/modules/ListCoeq/modules/CoeqDataTable/consts.tsx
- src/features/acf/frontend/hypertension/modules/AcfPage/modules/List/modules/ListCoeq/modules/CoeqDataTable/index.tsx
- src/features/acf/frontend/hypertension/modules/AcfPage/modules/List/modules/common/GoodPracticesSumFormatter/index.tsx
> [FEATURE] Adiciona colunas da versão beta no DataGrid

- src/features/acf/frontend/common/Print/modules/PrintTable/modules/Thead.tsx
- src/features/acf/frontend/hypertension/modules/AcfPage/modules/List/modules/ListCoaps/modules/Print/consts.tsx
- src/features/acf/frontend/hypertension/modules/AcfPage/modules/List/modules/ListCoeq/modules/Print/consts.tsx
> corrige quebra de linha na coluna de boas praticas da impressao

- src/features/acf/frontend/hypertension/modules/AcfPage/modules/List/modules/ListCoaps/modules/Print/consts.tsx
- src/features/acf/frontend/hypertension/modules/AcfPage/modules/List/modules/ListCoeq/modules/Print/consts.tsx
> corrige o titulo da lista nominal de hipertensao na impressao

- src/features/acf/frontend/common/Print/modules/PrintTable/presentation.tsx
- src/features/acf/frontend/common/WithCustomPrint/consts.ts
- src/features/acf/frontend/common/WithCustomPrint/context.ts
- src/features/acf/frontend/common/WithCustomPrint/index.tsx
> modifica PrintTable para usar o  context de visibilidade do modal e o context de customização

- __tests__/integration/api/cofin25/indicadores/cuidado_da_pessoa_com_diabetes/coaps/dados/route.test.ts
- __tests__/integration/api/cofin25/indicadores/cuidado_da_pessoa_com_diabetes/coeq/dados/route.test.ts
- src/app/api/cofin25/indicadores/cuidado_da_pessoa_com_diabetes/coaps/dados/route.ts
- src/app/api/cofin25/indicadores/cuidado_da_pessoa_com_diabetes/coeq/dados/route.ts
> [FEATURE] Adiciona Endpoints para dados de impressão

- src/features/acf/frontend/hypertension/modules/AcfPage/consts.tsx
> Ajuste texto descritivo da lista para versão com todas boas práticas.tsx
