- pages/_app.js
Pensando no tamanho da navegação e na estrutura do footer, foi-se alterado as opções de navegação para incluir apenas a página "A Impulso Gov" e "Termos de uso e politica de privacidade."
> Altera estrutura do Footer para conter apenas páginas da Impulso e Termos

- componentes/ModalAutorizacoes/ModalAutorizacoes.jsx
- componentes/ModalCadastroUsuario/ModalCadastroUsuario.jsx
A página de gestão de usuários passou a quebrar ao abrir os modais de edição de autorizações e de adição de novos usuários.
A razão para a página quebrar é que, com a atualização recente do design system no repositório, o componente `TituloSmallTexto` passou a ter novas props que não estava sendo passadas para o componente na página de gestão de usuários.
Atualização das props do componente `TituloSmallTexto` na página de gestão de usuários.
> [Fix] Atualiza props de TituloSmallTexto em gestão de usuários

- package.json
- pages/_app.js
- yarn.lock
Deve ter rolado algum conflito que no merge removeu o script do hotjar que estava instalado. Apenas reinstalei o script do hotjar para voltar ao funcionamento normal de gravações e heatmaps.
Como base, tomei como referência o seguinte artigo:
https://medium.com/@romansorin/using-hotjar-and-google-analytics-with-next-js-to-track-behavior-a2283d659767
> 📈 reinstall hotjar in _app.js

- componentes/GraficoHistoricoAcaoEstrategica/GraficoHistoricoAcaoEstrategica.jsx
- componentes/GraficoValorConsolidado/GraficoValorConsolidado.jsx
- componentes/TabelaIndicadores/TabelaIndicadores.jsx
- componentes/indicadores/index.js
- pages/_app.js
Com a disponibilização dos dados do Q3 2023, é necessário ajustar alguns textos na plataforma.
- Alterar os textos nos componentes da área aberta listados [aqui](https://www.notion.so/impulsogov/Checklist-Mudan-a-de-quadrimestre-IP-c009e7825ae4457698d2b979bbd426c5)
- Exibir em pt-br as abreviações dos meses nos gráficos de ações estratégicas
> Ajustes textos Q3 2023 na área aberta

- pages/inicio/index.js
A cada três meses ativamos um modal com um NPS pra medir a satisfação dos usuários com os recursos disponíveis na área logada.
- Desativar modal com NPS até o próximo ciclo de avaliações
> remove NPS

- pages/gestao-usuarios/cadastro/individual/index.js
- pages/gestao-usuarios/cadastro/lotes/index.js
- pages/gestao-usuarios/index.js
Com o lançamento das novas páginas de gestão de usuários, foram adicionados mecanismos para garantir que usuários não autenticados acessem as novas páginas. Porém, para que esses mecanismos funcionassem corretamente, era necessário que algumas dependências fossem importadas.
- Importar função de `signOut` nas novas páginas de gestão de usuários
- Instanciar um `router` nas novas páginas de gestão de usuários
> [Gestão de usuários] Adiciona importações ausentes

- pages/_app.js
A regra que define se um usuário é de teste ou não, no mixpanel, não estava funcionando corretamente, o que fez com que os usuários de teste não fossem identificados como tal, impactando a análise dos usuários que acessam a plataforma.
- Corrigir regra que define um usuário como de teste para considerar todos aqueles que:
- possuem o cargo _Impulser_
- ou possuem email contendo _@impulsogov.org_
- ou possuem município contendo _Impulsolândia_
> Corrige regra de usuário teste mixpanel

- package.json
- pages/busca-ativa/citopatologico/index.js
- pages/busca-ativa/diabeticos/index.js
- pages/busca-ativa/gestantes/index.js
- pages/busca-ativa/hipertensos/index.js
- pages/busca-ativa/vacinacao/index.js
- yarn.lock
Embora a fonte Inter seja aplicada às tabelas de impressão diretamente no design system, ela não é aplicada quando a tabela é exibida no site do IP porque fontes e outros estilos importados não são executados na versão de impressão das tabelas. Por isso, é aplicada a fonte padrão do navegador, que possui serifa, o que dificulta a leitura dos dados na versão de impressão, sendo necessário aplicar alguma fonte sem serifa.
- Aplicar fonte _sans-serif_ nas tabelas de impressão a partir da prop `fontFamily`
> Adiciona fonte sem serifa nas tabelas de impressão

- componentes/mounted/busca-ativa/gestantes/APS/indicador_1/grafico_indicador_1_atual.js
- componentes/mounted/busca-ativa/gestantes/APS/indicador_1/grafico_indicador_1_futuro.js
- componentes/mounted/busca-ativa/gestantes/APS/indicador_2/grafico_indicador_2_atual.js
- componentes/mounted/busca-ativa/gestantes/APS/indicador_2/grafico_indicador_2_futuro.js
- componentes/mounted/busca-ativa/gestantes/APS/indicador_3/grafico_indicador_3_atual.js
- componentes/mounted/busca-ativa/gestantes/APS/indicador_3/grafico_indicador_3_futuro.js
- componentes/mounted/busca-ativa/vacinacao/aps/proximo_quadrimestre/graficoQuadrimestreProximo.js
- componentes/mounted/busca-ativa/vacinacao/aps/proximo_quadrimestre/tabelaQuadrimestreProximo.js
- componentes/mounted/busca-ativa/vacinacao/aps/quadrimestre_atual/graficoQuadrimestreAtual.js
- componentes/mounted/busca-ativa/vacinacao/aps/quadrimestre_atual/tabelaQuadrimestreAtual.js
- componentes/mounted/busca-ativa/vacinacao/aps/quadrimestre_futuro/graficoQuadrimestreFuturo.js
- componentes/mounted/busca-ativa/vacinacao/aps/quadrimestre_futuro/tabelaQuadrimestreFuturo.js
- componentes/mounted/busca-ativa/vacinacao/equipe/proximo_quadrimestre/tabelaQuadrimestreProximo.js
- componentes/mounted/busca-ativa/vacinacao/equipe/quadrimestre_atual/tabelaQuadrimestreAtual.js
- componentes/mounted/busca-ativa/vacinacao/equipe/quadrimestre_futuro/tabelaQuadrimestreFuturo.js
- pages/busca-ativa/citopatologico/index.js
- pages/busca-ativa/diabeticos/index.js
- pages/busca-ativa/gestantes/index.js
- pages/busca-ativa/hipertensos/index.js
- utils/quadrimestre.js
Hoje foi notificado, [junto ao bug da data de produção mais recente na lista de vacinação](https://impulsogov.slack.com/archives/C04G8VCAC2G/p1709658815711899), que o texto do quadrimestre não estava correto na lista de vacinação, visão de APS, do município de Campos Novos - SC.
A causa desse problema foi a seguinte:
- Quando os textos de quadrimestre foram dinamizados, era selecionada a data de produção do primeiro elemento da lista de dados. Para o município Campo Novos - SC, esse primeiro elemento tinha data nula, o que gerava um objeto do tipo Date com ano igual 1970, por isso era mostrado o texto **Q1/70**.
**_IMPORTANTE_**: Em conversa com o time, entendemos que deveria ser usada a data atual para gerar os quadrimestres, e não a data de produção.
- Usar a data atual para gerar os …
> [Área restrita] Corrige data usada para gerar quadrimestres

- componentes/ModalCadastroUsuario/ModalCadastroUsuario.jsx
- constants/gestaoUsuarios.js
- constants/municipios.js
Recentemente, o nome do município demo do Impulso Previne foi atualizado, então é necessário atualizar seu nome também no JSON usado para exibir as opções de municípios na gestão de usuários.
Além disso, houve também a necessidade de adicionar uma nova opção de cargo para cadastro de usuários.
- Atualizar o nome do município demo para _Demo - Bonfim_ e sua uf para _RR_ no JSON de municípios
- Adicionar o cargo _Coordenador (a) de Vigilância Epidemiológica_ nas opções de cargo
- Aumentar a largura do seletor de cargo para ser possível ler os nomes de cargos por completo
> [Gestão de usuários] Adiciona cargo e atualiza nome da demo

- pages/apoio/index.js
- pages/index.js
Na [[página principal](https://www.impulsoprevine.org/)](https://www.impulsoprevine.org/),  2 ajustes:
- na parte de **Conteúdos gratuitos**, mudança de botão de "Ver materiais" para "Receber materiais" e mudança de link para [[formulário de inscrição no CRM](https://docs.google.com/forms/d/e/1FAIpQLSdMuW8LG3MB8RsR2B9GrjsPez4WPp7SqOaLiXb1kmMOuspmkw/viewform)](https://docs.google.com/forms/d/e/1FAIpQLSdMuW8LG3MB8RsR2B9GrjsPez4WPp7SqOaLiXb1kmMOuspmkw/viewform).
- Mudança de link final de "Fazer inscrição na lista" para [[formulário de inscrição no CRM](https://docs.google.com/forms/d/e/1FAIpQLSdMuW8LG3MB8RsR2B9GrjsPez4WPp7SqOaLiXb1kmMOuspmkw/viewform)](https://docs.google.com/forms/d/e/1FAIpQLSdMuW8LG3MB8RsR2B9GrjsPez4WPp7SqOaLiXb1kmMOuspmkw/viewform) 
E na [[página de apoio aos …
> ALTERAÇÕES DE LINKS E TEXTOS SOLICITADOS

- pages/inicio/index.js
https://www.notion.so/impulsogov/Alterar-layout-da-tela-inicial-invertendo-a-ordem-dos-cards-deixar-cards-de-listas-acima-dos-cards-52ec830d242f4b63a173c272dde3a64a?pvs=4
- Posicionar os cards das listas nominais e dos cadastros acima dos cards de trilha
> Inverte ordem dos cards de início

- package.json
- yarn.lock
- Considerando o alto numero de disparos realizados pelo evento de digitação de caracteres não numéricos no login, conforme indicado nessa [thread](https://impulsogov.slack.com/archives/C05FNRDAJDA/p1714494461602409?thread_ts=1714494333.394589&cid=C05FNRDAJDA), se tornou muito alto para o plano contratado no mixpanel, sendo assim os times de analise e produto decidiram remover esse evento.
- Remover o evento
> Remove evento de alerta de digitação de caracteres não numéricos no login

- package.json
- pages/busca-ativa/gestantes/index.js
- yarn.lock
[Descrição da tarefa](https://www.notion.so/impulsogov/Aplicar-quebra-de-linha-no-texto-das-abas-do-seletor-de-pain-is-apenas-na-lista-de-pr-natal-ac34eb0258854a39933c7f332169b056?pvs=4)
- Adicionar prop que quebra linha dos textos de aba e subaba do seletor de painéis na lista de pré-natal, visão APS
> Quebra texto das abas na lista de pré-natal

- componentes/mounted/busca-ativa/gestantes/APS/indicador_1/grafico_indicador_1_atual.js
- componentes/mounted/busca-ativa/gestantes/APS/indicador_2/grafico_indicador_2_atual.js
- componentes/mounted/busca-ativa/gestantes/APS/indicador_3/grafico_indicador_3_atual.js
Notou-se que o painel de pré-natal estava exibindo valores zerados nas abas do quadrimestre atual (Q2/2024) nos 3 indicadores.
- Atualizar nome do quadrimestre usado para filtrar os dados nas abas do quadrimestre atual
> [Pré-natal] Corrige visualizações do quadrimestre atual

- package.json
- pages/analise/index.js
- pages/dadoPublicos/index.js
- pages/index.js
- pages/quem-somos/index.js
- yarn.lock
[Detalhes da tarefa](https://www.notion.so/impulsogov/Pacote-5-PB-Desenvolvimento-e7bc812f4a2746b482c1200488229a55?pvs=4)
- Remover seção sobre análises do previne na página inicial
- Remover card sobre dados do SISAB na página Quem somos
- Incluir mensagem sobre fim do Previne Brasil nas páginas de dados públicos
> [Quick wins] Pacote 5

- pages/_app.js
Ultimamente, houve a necessidade de aplicar pesquisas no Impulso Previne a partir do Hotjar e, para isso, se tornou necessário fazer algumas configurações para seu uso.
- Definir atributos de usuário que são enviados ao hotjar
- Expor o mixpanel globalmente para permitir sua integração com o hotjar
> [Hotjar] Configura atributos de usuário e expõe mixpanel

- pages/cadastros-duplicados/index.js
Ultimamente, houve a necessidade de aplicar pesquisas no Impulso Previne a partir do Hotjar e, para isso, se tornou necessário fazer algumas configurações para seu uso.
- Disparar evento via API do hotjar para avaliar seu uso no controle de pesquisas
- Validar uso de eventos do hotjar com integração de hotjar + mixpanel
> [Hotjar] Adiciona evento em cadastros duplicados

- pages/_app.js
- pages/cadastros-duplicados/index.js
- Remover evento da página de cadastros duplicados
- Adicionar evento no click do botão de gestão de usuários
> [Hotjar] Altera disparo de evento

- helpers/eventosImpressaoHotjar.js
- package.json
- pages/_app.js
- pages/cadastros-duplicados/index.js
- yarn.lock
Anteriormente, usávamos a biblioteca `react-hotjar` para enviar dados ao hotjar e disparar eventos, mas percebemos que ela não estava funcionando corretamente, além de não ser a biblioteca oficial do hotjar.
- Usar a biblioteca oficial `@hotjar/browser` no código para integração com hotjar
- Desinstalar biblioteca `react-hotjar`
- Adicionar o id do site como variável de ambiente
> Altera biblioteca do hotjar

- componentes/mounted/busca-ativa/vacinacao/aps/proximo_quadrimestre/tabelaQuadrimestreProximo.js
- componentes/mounted/busca-ativa/vacinacao/aps/quadrimestre_atual/tabelaQuadrimestreAtual.js
- componentes/mounted/busca-ativa/vacinacao/aps/quadrimestre_futuro/tabelaQuadrimestreFuturo.js
- package.json
- pages/busca-ativa/vacinacao/index.js
- yarn.lock
Os eventos das listas de vacinação disparados para o mixpanel estavam exibindo strings vazias nas propriedades de `aba_lista_nominal` e `sub_aba_lista_nominal` ao invés dos números de aba e sub-aba. Isso aconteceu porque os componentes das listas de vacinação não estavam recebendo esses valores para adicionar nos eventos disparados.
Além disso, o evento `aplicar_filtro` não estava exibindo o nome da lista nominal corretamente.
- Passar os números de aba e sub-aba para o componente das listas de vacinação
- Atualizar design system para incorporar correção do evento `aplicar_filtro`
> Corrige eventos de vacinação e aplicar_filtro

- componentes/mounted/busca-ativa/citopatologico/APS/TabelaAPSComExame.jsx
- componentes/mounted/busca-ativa/citopatologico/APS/TabelaAPSSemExame.jsx
- componentes/mounted/busca-ativa/gestantes/APS/GestantesSemDUM/GestantesSemDum.js
- componentes/mounted/busca-ativa/gestantes/APS/indicador_1/tabelas/GestantesAtivas.js
- componentes/mounted/busca-ativa/gestantes/APS/indicador_1/tabelas/GestantesEncerradas.js
- componentes/mounted/busca-ativa/gestantes/APS/indicador_2/tabelas/GestantesAtivas.js
- componentes/mounted/busca-ativa/gestantes/APS/indicador_2/tabelas/GestantesEncerradas.js
- componentes/mounted/busca-ativa/gestantes/APS/indicador_3/tabelas/GestantesAtivas.js
- componentes/mounted/busca-ativa/gestantes/APS/indicador_3/tabelas/GestantesEncerradas.js
- componentes/mounted/busca-ativa/vacinacao/aps/proximo_quadrimestre/tabelaQuadrimestreProximo.js
- componentes/mounted/busca-ativa/vacinacao/aps/quadrimestre_atual/tabelaQuadrimestreAtual.js
- componentes/mounted/busca-ativa/vacinacao/aps/quadrimestre_futuro/tabelaQuadrimestreFuturo.js
[Descrição da tarefa](https://linear.app/impulsogov/issue/ALOG-38/coaps-inserir-a-informacao-da-aba-da-lista-nominal-no-titulo-da-folha)
- Atualizar títulos das listas impressas de Citopatológico, Pré-natal e Vacinação, visão APS, para inserir informações de suas abas
> Adiciona informação de aba no título das listas impressas

- .coderabbit.yaml
Altera o coderabbit para não fazer review automático, deixando nossos PRs um pouco menos poluídos.
Ele ainda pode ser triggado comentando @coderabbit review no PR.
> Altera configurações do Coderabbit

- src/app/inicio/CardsGrid.tsx
https://linear.app/impulsogov/issue/ALOG-380/urgente-descricao-errada-nos-cards-de-lembretes
> fix: Corrige descrições dos cards de citopatológico e hipertensão da página inicial  

- jest.config.ts
- jest.setup.ts
Toda vez que fazemos um teste que renderiza componentes na tela sem mockar (especialmente do design system), estamos recebendo erros de importação do `MessageChannel`. Ao corrigir este erro, o mesmo acontece com `TextEncoder` e `TextDecoder`.
Este PR corrige ambos os problemas, liberando este tipo de teste para o futuro.
> Corrige problemas de importação em MessageChannel e TextEncoder/Decoder quando rodando testes do jest

- src/features/acf/backend/hypertension/modules/filters/repository.ts
- src/features/acf/frontend/hypertension/modules/AcfPage/modules/List/modules/CoapsFiltersBar/logic.ts
- src/features/acf/frontend/hypertension/modules/AcfPage/modules/List/modules/common/SharedSelectConfigs.ts
Este PR ordena as opções de filtro exibidos na página de hipertensão dentro do repository do endpoint de filtros.
Fixes ALOG-520, ALOG-514
> Ordena opções de filtro no backend

- .github/workflows/pr-integration-test.yml
- .github/workflows/pr-unit-test.yml
- package.json
A partir do PR https://github.com/ImpulsoGov/ImpulsoPrevine/pull/489, tornou-se necessário separar as actions que executam os testes da aplicação, já que agora temos também testes de integração.
Este PR adiciona a action de teste unitário e a de teste de integração.
Fixes ALOG-580
> Separa actions de teste

- __tests__/helpers/auth.ts
- __tests__/helpers/db.ts
- __tests__/helpers/flag.ts
- __tests__/integration/api/lista-nominal/hypertension/filters/coaps/route.test.ts
- __tests__/integration/api/lista-nominal/hypertension/filters/coeq/route.test.ts
Este PR adiciona testes de integração para os endpoints `/api/lista-nominal/hypertension/filters/coaps` e `/api/lista-nominal/hypertension/filters/coeq`, além de:
- Criar um helper genérico para fazer mock das flags
- **OBS:** a substituição e remoção do helper `mockDiabetesNewProgram` será feita num PR separado para manter os PRs com uma quantidade razoável de mudanças.
Fixes ALOG-579
> Adiciona teste de integração da rota de filtros de hipertensão
